export const CASE_REPOSITORY = Symbol('CASE_REPOSITORY');
export const CLIENT_REPOSITORY = Symbol('CLIENT_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const FILE_BATCH_REPOSITORY = Symbol('FILE_BATCH_REPOSITORY');
export const CASE_FILE_REPOSITORY = Symbol('CASE_FILE_REPOSITORY');
export const STORAGE_PORT = Symbol('STORAGE_PORT');
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');
